@@include('jquery.inputmask.bundle.min.js') 
@@include('jquery.nicescroll.min.js')
@@include('jquery.ui.touch-punch.min.js')
@@include('jquery.popover.min.js')
@@include('baguetteBox.js')
@@include('slick.min.js')